# Site settings
title: 💥🔥📘
baseurl: ""
url: "http://journal.henrykaufman.me"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: UA-64318963-6
disqus_shortname:
