# Site settings
title: d.reams
baseurl: ""
url: "http://d.reams.org"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
