# Site settings
title: Journal
baseurl: ""
url: "http://journal.henrykaufman.me"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 
